var quotes = [
    `“Time is a created thing. To say ‘I don’t have time’ is to say ‘I don’t want to.'” – Lao Tzu`,
    `“To achieve great things, two things are needed; a plan, and not quite enough time.” – Leonard Bernstein`,
    `“Don’t say you don’t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michaelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.” – H. Jackson Brown`,
    `“The only reason for time is so that everything doesn’t happen at once.” – Albert Einstein`,
    `“The best thing about the future is that it comes one day at a time.”- Abraham Lincoln`,
    `“Take time to deliberate; but when the time for action arrives, stop thinking and go in.” – Napoleon Bonaparte`,
    `“Time isn’t precious at all, because it is an illusion.” – Eckhart Tolle`,
    `“Time is more valuable than money. You can get more money, but you cannot get more time.” – Jim Rohn`,
    `“Defer no time, delays have dangerous ends.” – William Shakespeare`,
    `“Time is what we want most, but what we use worst.” – William Penn`,
    `“Time is but the stream I go a-fishing in.” – Henry David Thoreau`,
    `“Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.” – Henry Van Dyke`,
    `“You may delay, but time will not.” – Ben Franklin`,
    `“If you want work well done, select a busy man — the other kind has no time.” – Elbert Hubbard`,
    `“What then is time? If no one asks me, I know what it is. If I wish to explain it to him who asks, I do not know.” – Saint Augustine`,
    `“Pick my left pocket of its silver dime, but spare the right — it holds my golden time!” – Oliver Wendell Holmes`,
    `“Both young children and old people have a lot of time on their hands. That’s probably why they get along so well.” – Jonathan Carroll`,
    `“My time is now.” – John Turner"`,
    `“All my possessions for a moment of time.” – Queen Elizabeth`,
    `“What may be done at any time will be done at no time.” – Scottish proverb`,
    `“Half our life is spent trying to find something to do with the time we have rushed through life trying to save.” – Will Rogers`,
    `“Time flies like an arrow. Fruit flies like a banana.” – Groucho Marx`,
    `“I’ve been on a calendar, but I have never been on time.” – Marilyn Monroe`,
    `“The surest way to be late is to have plenty of time.” – Leo Kennedy`,
    `“A committee is a group that keeps minutes and loses hours.” – Milton Berle`,
    `“The future has already arrived. It’s just not evenly distributed yet.” – William Gibson`,
    `“The key is in not spending time, but in investing it.” – Stephen Covey`,
    `“It’s not enough to be busy, so are the ants. The question is, what are we busy about?” – Henry David Thoreau`,
    `“Take care of the minutes and the hours will take care of themselves.” – Lord Chesterfield`,
    `“In truth, people can generally make time for what they choose to do; it is not really the time but the will that is lacking.” – Sir John Lubbock`,
    `“I am definitely going to take a course on time management — just as soon as I can work it into my schedule.” – Louis Boone`,
    `“You will never ‘find’ time for anything. If you want time, you must make it.” – Charles Bruxton`,
    `“The bad news is time flies. The good news is you’re the pilot.” – Michael Altshule`,
    `“Time is really the only capital that any human being has, and the only thing he can’t afford to lose.” – Thomas Edison`,
    `“The time for action is now. It’s never too late to do something.” – Carl Sandburg`
];


export default quotes
